name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

env:
    GO111MODULE: "on"

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go 1.19
              uses: actions/setup-go@v3
              with:
                  go-version: "1.19"

            - name: Run Go linters
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.42

    test:
        needs:
            - lint

        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest

                go:
                    # "1.10" doesn't support modules.
                    - "1.11"
                    # ...
                    - "1.17"
                    - "1.18"
                    - "1.19"

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go ${{ matrix.go }}
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go }}

            - name: Download Go dependencies
              run: go mod download

            - name: Run tests
              run: go test -race -covermode=atomic -coverprofile=coverage -v ./...

            - uses: codecov/codecov-action@v3
              with:
                  files: ./coverage
                  flags: unittests,${{ matrix.os }},go${{ matrix.go }}
                  verbose: true
