name: CI

on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    # - macos-latest
                    # - windows-latest

                go:
                    # - "1.10"
                    - "1.16"
                    # - "1.17"
                    # - "1.18"
                    # - "1.19"

                chapter:
                    - 001_redis_protocol

        defaults:
            run:
                working-directory: ${{ matrix.chapter }}/radish

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go ${{ matrix.go }}
              uses: actions/setup-go@v3
              with:
                  go-version: ${{ matrix.go }}

            - run: go version

            - name: Set up Cover cmd
              run: go get golang.org/x/tools/cmd/cover

            - name: Run tests
              run: go test -race -covermode=atomic -coverprofile=coverage -v ./...

            - uses: codecov/codecov-action@v3
              with:
                  files: ${{ matrix.chapter }}/radish/coverage
                  flags: unittests,${{ matrix.os }},go${{ matrix.go }},${{ matrix.chapter }}
                  fail_ci_if_error: true
                  verbose: true
